/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as ServiciosPublicosRouteImport } from './routes/servicios-publicos'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as DirectorioRouteImport } from './routes/directorio'
import { Route as ClasificadosRouteImport } from './routes/clasificados'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccederRouteImport } from './routes/acceder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosPublicosIndexRouteImport } from './routes/servicios-publicos.index'
import { Route as ServiciosPublicosSlugRouteImport } from './routes/servicios-publicos.$slug'
import { Route as NoticiasPublicarRouteImport } from './routes/noticias.publicar'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as MarketplacePublicarRouteImport } from './routes/marketplace.publicar'
import { Route as ClasificadosPublicarRouteImport } from './routes/clasificados.publicar'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosPublicosRoute = ServiciosPublicosRouteImport.update({
  id: '/servicios-publicos',
  path: '/servicios-publicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorioRoute = DirectorioRouteImport.update({
  id: '/directorio',
  path: '/directorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasificadosRoute = ClasificadosRouteImport.update({
  id: '/clasificados',
  path: '/clasificados',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccederRoute = AccederRouteImport.update({
  id: '/acceder',
  path: '/acceder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosPublicosIndexRoute = ServiciosPublicosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiciosPublicosRoute,
} as any)
const ServiciosPublicosSlugRoute = ServiciosPublicosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServiciosPublicosRoute,
} as any)
const NoticiasPublicarRoute = NoticiasPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => NoticiasRoute,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NoticiasRoute,
} as any)
const MarketplacePublicarRoute = MarketplacePublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => MarketplaceRoute,
} as any)
const ClasificadosPublicarRoute = ClasificadosPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => ClasificadosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceder': typeof AccederRoute
  '/admin': typeof AdminRoute
  '/clasificados': typeof ClasificadosRouteWithChildren
  '/directorio': typeof DirectorioRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/noticias': typeof NoticiasRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/publicar': typeof PublicarRoute
  '/servicios-publicos': typeof ServiciosPublicosRouteWithChildren
  '/shopping': typeof ShoppingRoute
  '/terminos': typeof TerminosRoute
  '/clasificados/publicar': typeof ClasificadosPublicarRoute
  '/marketplace/publicar': typeof MarketplacePublicarRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/noticias/publicar': typeof NoticiasPublicarRoute
  '/servicios-publicos/$slug': typeof ServiciosPublicosSlugRoute
  '/servicios-publicos/': typeof ServiciosPublicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceder': typeof AccederRoute
  '/admin': typeof AdminRoute
  '/clasificados': typeof ClasificadosRouteWithChildren
  '/directorio': typeof DirectorioRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/noticias': typeof NoticiasRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/publicar': typeof PublicarRoute
  '/shopping': typeof ShoppingRoute
  '/terminos': typeof TerminosRoute
  '/clasificados/publicar': typeof ClasificadosPublicarRoute
  '/marketplace/publicar': typeof MarketplacePublicarRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/noticias/publicar': typeof NoticiasPublicarRoute
  '/servicios-publicos/$slug': typeof ServiciosPublicosSlugRoute
  '/servicios-publicos': typeof ServiciosPublicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceder': typeof AccederRoute
  '/admin': typeof AdminRoute
  '/clasificados': typeof ClasificadosRouteWithChildren
  '/directorio': typeof DirectorioRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/noticias': typeof NoticiasRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/publicar': typeof PublicarRoute
  '/servicios-publicos': typeof ServiciosPublicosRouteWithChildren
  '/shopping': typeof ShoppingRoute
  '/terminos': typeof TerminosRoute
  '/clasificados/publicar': typeof ClasificadosPublicarRoute
  '/marketplace/publicar': typeof MarketplacePublicarRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/noticias/publicar': typeof NoticiasPublicarRoute
  '/servicios-publicos/$slug': typeof ServiciosPublicosSlugRoute
  '/servicios-publicos/': typeof ServiciosPublicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceder'
    | '/admin'
    | '/clasificados'
    | '/directorio'
    | '/marketplace'
    | '/noticias'
    | '/privacidad'
    | '/publicar'
    | '/servicios-publicos'
    | '/shopping'
    | '/terminos'
    | '/clasificados/publicar'
    | '/marketplace/publicar'
    | '/noticias/$slug'
    | '/noticias/publicar'
    | '/servicios-publicos/$slug'
    | '/servicios-publicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceder'
    | '/admin'
    | '/clasificados'
    | '/directorio'
    | '/marketplace'
    | '/noticias'
    | '/privacidad'
    | '/publicar'
    | '/shopping'
    | '/terminos'
    | '/clasificados/publicar'
    | '/marketplace/publicar'
    | '/noticias/$slug'
    | '/noticias/publicar'
    | '/servicios-publicos/$slug'
    | '/servicios-publicos'
  id:
    | '__root__'
    | '/'
    | '/acceder'
    | '/admin'
    | '/clasificados'
    | '/directorio'
    | '/marketplace'
    | '/noticias'
    | '/privacidad'
    | '/publicar'
    | '/servicios-publicos'
    | '/shopping'
    | '/terminos'
    | '/clasificados/publicar'
    | '/marketplace/publicar'
    | '/noticias/$slug'
    | '/noticias/publicar'
    | '/servicios-publicos/$slug'
    | '/servicios-publicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccederRoute: typeof AccederRoute
  AdminRoute: typeof AdminRoute
  ClasificadosRoute: typeof ClasificadosRouteWithChildren
  DirectorioRoute: typeof DirectorioRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  NoticiasRoute: typeof NoticiasRouteWithChildren
  PrivacidadRoute: typeof PrivacidadRoute
  PublicarRoute: typeof PublicarRoute
  ServiciosPublicosRoute: typeof ServiciosPublicosRouteWithChildren
  ShoppingRoute: typeof ShoppingRoute
  TerminosRoute: typeof TerminosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios-publicos': {
      id: '/servicios-publicos'
      path: '/servicios-publicos'
      fullPath: '/servicios-publicos'
      preLoaderRoute: typeof ServiciosPublicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directorio': {
      id: '/directorio'
      path: '/directorio'
      fullPath: '/directorio'
      preLoaderRoute: typeof DirectorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasificados': {
      id: '/clasificados'
      path: '/clasificados'
      fullPath: '/clasificados'
      preLoaderRoute: typeof ClasificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceder': {
      id: '/acceder'
      path: '/acceder'
      fullPath: '/acceder'
      preLoaderRoute: typeof AccederRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios-publicos/': {
      id: '/servicios-publicos/'
      path: '/'
      fullPath: '/servicios-publicos/'
      preLoaderRoute: typeof ServiciosPublicosIndexRouteImport
      parentRoute: typeof ServiciosPublicosRoute
    }
    '/servicios-publicos/$slug': {
      id: '/servicios-publicos/$slug'
      path: '/$slug'
      fullPath: '/servicios-publicos/$slug'
      preLoaderRoute: typeof ServiciosPublicosSlugRouteImport
      parentRoute: typeof ServiciosPublicosRoute
    }
    '/noticias/publicar': {
      id: '/noticias/publicar'
      path: '/publicar'
      fullPath: '/noticias/publicar'
      preLoaderRoute: typeof NoticiasPublicarRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/marketplace/publicar': {
      id: '/marketplace/publicar'
      path: '/publicar'
      fullPath: '/marketplace/publicar'
      preLoaderRoute: typeof MarketplacePublicarRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/clasificados/publicar': {
      id: '/clasificados/publicar'
      path: '/publicar'
      fullPath: '/clasificados/publicar'
      preLoaderRoute: typeof ClasificadosPublicarRouteImport
      parentRoute: typeof ClasificadosRoute
    }
  }
}

interface ClasificadosRouteChildren {
  ClasificadosPublicarRoute: typeof ClasificadosPublicarRoute
}

const ClasificadosRouteChildren: ClasificadosRouteChildren = {
  ClasificadosPublicarRoute: ClasificadosPublicarRoute,
}

const ClasificadosRouteWithChildren = ClasificadosRoute._addFileChildren(
  ClasificadosRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplacePublicarRoute: typeof MarketplacePublicarRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplacePublicarRoute: MarketplacePublicarRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface NoticiasRouteChildren {
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  NoticiasPublicarRoute: typeof NoticiasPublicarRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasSlugRoute: NoticiasSlugRoute,
  NoticiasPublicarRoute: NoticiasPublicarRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

interface ServiciosPublicosRouteChildren {
  ServiciosPublicosSlugRoute: typeof ServiciosPublicosSlugRoute
  ServiciosPublicosIndexRoute: typeof ServiciosPublicosIndexRoute
}

const ServiciosPublicosRouteChildren: ServiciosPublicosRouteChildren = {
  ServiciosPublicosSlugRoute: ServiciosPublicosSlugRoute,
  ServiciosPublicosIndexRoute: ServiciosPublicosIndexRoute,
}

const ServiciosPublicosRouteWithChildren =
  ServiciosPublicosRoute._addFileChildren(ServiciosPublicosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccederRoute: AccederRoute,
  AdminRoute: AdminRoute,
  ClasificadosRoute: ClasificadosRouteWithChildren,
  DirectorioRoute: DirectorioRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  NoticiasRoute: NoticiasRouteWithChildren,
  PrivacidadRoute: PrivacidadRoute,
  PublicarRoute: PublicarRoute,
  ServiciosPublicosRoute: ServiciosPublicosRouteWithChildren,
  ShoppingRoute: ShoppingRoute,
  TerminosRoute: TerminosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
