/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as ServiciosPublicosRouteImport } from './routes/servicios-publicos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as DirectorioRouteImport } from './routes/directorio'
import { Route as ClasificadosRouteImport } from './routes/clasificados'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiasPublicarRouteImport } from './routes/noticias.publicar'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosPublicosRoute = ServiciosPublicosRouteImport.update({
  id: '/servicios-publicos',
  path: '/servicios-publicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorioRoute = DirectorioRouteImport.update({
  id: '/directorio',
  path: '/directorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasificadosRoute = ClasificadosRouteImport.update({
  id: '/clasificados',
  path: '/clasificados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasPublicarRoute = NoticiasPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => NoticiasRoute,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NoticiasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clasificados': typeof ClasificadosRoute
  '/directorio': typeof DirectorioRoute
  '/marketplace': typeof MarketplaceRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/servicios-publicos': typeof ServiciosPublicosRoute
  '/shopping': typeof ShoppingRoute
  '/terminos': typeof TerminosRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/noticias/publicar': typeof NoticiasPublicarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clasificados': typeof ClasificadosRoute
  '/directorio': typeof DirectorioRoute
  '/marketplace': typeof MarketplaceRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/servicios-publicos': typeof ServiciosPublicosRoute
  '/shopping': typeof ShoppingRoute
  '/terminos': typeof TerminosRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/noticias/publicar': typeof NoticiasPublicarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clasificados': typeof ClasificadosRoute
  '/directorio': typeof DirectorioRoute
  '/marketplace': typeof MarketplaceRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/servicios-publicos': typeof ServiciosPublicosRoute
  '/shopping': typeof ShoppingRoute
  '/terminos': typeof TerminosRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/noticias/publicar': typeof NoticiasPublicarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clasificados'
    | '/directorio'
    | '/marketplace'
    | '/noticias'
    | '/privacidad'
    | '/servicios-publicos'
    | '/shopping'
    | '/terminos'
    | '/noticias/$slug'
    | '/noticias/publicar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clasificados'
    | '/directorio'
    | '/marketplace'
    | '/noticias'
    | '/privacidad'
    | '/servicios-publicos'
    | '/shopping'
    | '/terminos'
    | '/noticias/$slug'
    | '/noticias/publicar'
  id:
    | '__root__'
    | '/'
    | '/clasificados'
    | '/directorio'
    | '/marketplace'
    | '/noticias'
    | '/privacidad'
    | '/servicios-publicos'
    | '/shopping'
    | '/terminos'
    | '/noticias/$slug'
    | '/noticias/publicar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClasificadosRoute: typeof ClasificadosRoute
  DirectorioRoute: typeof DirectorioRoute
  MarketplaceRoute: typeof MarketplaceRoute
  NoticiasRoute: typeof NoticiasRouteWithChildren
  PrivacidadRoute: typeof PrivacidadRoute
  ServiciosPublicosRoute: typeof ServiciosPublicosRoute
  ShoppingRoute: typeof ShoppingRoute
  TerminosRoute: typeof TerminosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios-publicos': {
      id: '/servicios-publicos'
      path: '/servicios-publicos'
      fullPath: '/servicios-publicos'
      preLoaderRoute: typeof ServiciosPublicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directorio': {
      id: '/directorio'
      path: '/directorio'
      fullPath: '/directorio'
      preLoaderRoute: typeof DirectorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasificados': {
      id: '/clasificados'
      path: '/clasificados'
      fullPath: '/clasificados'
      preLoaderRoute: typeof ClasificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/publicar': {
      id: '/noticias/publicar'
      path: '/publicar'
      fullPath: '/noticias/publicar'
      preLoaderRoute: typeof NoticiasPublicarRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof NoticiasRoute
    }
  }
}

interface NoticiasRouteChildren {
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  NoticiasPublicarRoute: typeof NoticiasPublicarRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasSlugRoute: NoticiasSlugRoute,
  NoticiasPublicarRoute: NoticiasPublicarRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClasificadosRoute: ClasificadosRoute,
  DirectorioRoute: DirectorioRoute,
  MarketplaceRoute: MarketplaceRoute,
  NoticiasRoute: NoticiasRouteWithChildren,
  PrivacidadRoute: PrivacidadRoute,
  ServiciosPublicosRoute: ServiciosPublicosRoute,
  ShoppingRoute: ShoppingRoute,
  TerminosRoute: TerminosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
